---
name: Validate JSONs

on  : [pull_request]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: brittonhayes/validate-yaml@v0.3.0
      with:
        schemaPath: './schema.json'
        files: |
          ./recipes/anejohighball.yaml

