---
name: Validate JSONs

on  : [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Validate YAML
      uses: brittonhayes/validate-yaml@v0.5.1
      with:
        schemaPath: schema.json
        files: |
          recipes/*
