---
name: Validate JSONs

on  : [pull_request]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nrkno/yaml-schema-validator-github-action@v4
      with:
        schema: ./schema.json
        target: ./recipes/

