---
name: Validate JSONs

on  : [pull_request]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: brittonhayes/validate-yaml
      with:
        schemaPath: './schema.json'
        files: |
          ./recipes/

