---
name: Validate JSONs

on  : [pull_request]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nwisbeta/validate-yaml-schema@v1.0.3
      with:
        yamlSchemasJson: |
          {
              "./schema.son": ["./recipes/*"],
          }

