---
name: Validate JSONs

on  : [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nwisbeta/validate-yaml-schema@v1.0.3
      with:
        yamlSchemasJson: |
          {
              "/schema.json": ["/recipes/*"],
          }
