---
name: Validate JSONs

on  : [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Validate YAML
    - uses: nwisbeta/validate-yaml-schema@v1.0.3
      with:
        yamlSchemasJson: |
          {
              "./schema.json": ["/recipes/*.yaml"],
          }
