---
name: Validate JSONs

on  : [pull_request]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: InoUno/yaml-ls-check@develop
      with:
        schemaMapping: |
          {
              "schema.json": [ "recipes/*.yaml" ]
          }

