---
name: Validate JSONs

on  : [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate YAML
      uses: brittonhayes/validate-yaml
      with:
        schemaPath: schema.json
        files: |
          recipes/*.yaml
